# Generated by Django 4.1 on 2025-04-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="leaderboard_id",
            field=models.CharField(
                default="default_leaderboard_id", max_length=100, unique=True
            ),
        ),
    ]
