# Generated by Django 4.1 on 2025-04-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_leaderboard_leaderboard_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="workout_id",
            field=models.CharField(
                default="default_workout_id", max_length=100, unique=True
            ),
        ),
    ]
